//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema2_Universitate
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDetails
    {
        public int RoomDetailID { get; set; }
        public int RoomNumber { get; set; }
        public string StudentCNP { get; set; }
        public Nullable<int> NumarStudenti { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual Students Students { get; set; }
    }
}
